services:
  mysql:
    from: mysql
    env:
      - MYSQL_DATABASE=edit-fu_staging
      - MYSQL_USER=edit-fu
      - MYSQL_PASSWORD=edit-fu
  rails:
    from: ruby:1.9.3
    cache:
      - /bundle
    env:
      - GEM_HOME=/bindle
    build:
      - apt-get update
      - apt-get install -y libqt4-dev pkg-config
      - apt-get install -y curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev libxml2-dev libxslt-dev

server:
  prepare:
    - rake db:create db:migrate
  service: rails
  folder: /app
  cmd: script/rails server -p 80
  port: 80
  env:
    - RAILS_ENV=production
    - RACK_ENV=production
